=== Macadoshis/stalker-to-m3u/tools/schemas/generator-config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "description": "Schema for generator-config.json file.",
  "properties": {
    "userAgent": {
      "type": "string",
      "description": "User-Agent for HTTP requests"
    },
    "geminiAiKey": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Array of 1 or many Google GEMINI AI key",
      "default": false
    },
    "geminiAiModel": {
      "type": "string",
      "description": "Google GEMINI AI model (supported by your key)",
      "default": "gemini-2.0-flash"
    },
    "outputDir": {
      "type": "string",
      "description": "Output directory of generated M3U files",
      "default": "."
    },
    "languages": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of languages to support criteria. Not applied if unset.",
      "default": []
    },
    "maxOutputs": {
      "type": "number",
      "description": "Max entries to generate from succeeded.json. Skipped existing m3u files are not considered.",
      "default": -1
    },
    "host": {
      "type": "string",
      "description": "Host to replay. If set, filters succeeded.json to given host."
    },
    "mac": {
      "type": "string",
      "description": "MAC to replay. If set, filters succeeded.json to given MAC."
    },
    "shuffle": {
      "type": "boolean",
      "description": "Shuffle succeeded.json entries to read from",
      "default": "false"
    },
    "iptv": {
      "type": "object",
      "properties": {
        "countries": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of countries for which to fetch channels for (ex. 'Live sports', 'Info', 'Kids'). They need to be spelled in English."
        },
        "excludedGroups": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of channels groups to exclude (ex. 'Music', 'Sports', 'SD channels'). They need to be spelled in English. Not applied if unset.",
          "default": []
        }
      },
      "required": [
        "countries"
      ]
    },
    "vod": {
      "type": "object",
      "properties": {
        "includedCategories": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of categories of VOD for which to fetch movies for (ex. 'Comedy', 'Paramount movies'). They need to be spelled in English."
        },
        "excludedCategories": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of categories of VOD to exclude (ex. 'Adults', 'Romance', 'Horror', 'Prime movies'). They need to be spelled in English. Not applied if unset.",
          "default": []
        }
      },
      "required": [
        "includedCategories"
      ]
    },
    "series": {
      "type": "object",
      "properties": {
        "includedSeries": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of series or themes of series to fetch (ex. : 'Punisher', 'Netflix'). They need to be spelled in English."
        },
        "excludedSeries": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of series or themes of series to exclude (ex. 'Disney+'). They need to be spelled in English. Not applied if unset.",
          "default": []
        }
      },
      "required": [
        "includedSeries"
      ]
    },
    "streamTester": {
      "type": "string",
      "description": "Stream tester mode",
      "anyOf": [
        {
          "const": "http",
          "title": "Check the endpoint liveness with HTTP"
        },
        {
          "const": "ffmpeg",
          "title": "Check the stream liveness with FFMPEG"
        }
      ],
      "default": "ffmpeg"
    }
  },
  "required": [
    "geminiAiKey"
  ],
  "additionalProperties": false
}

=== Macadoshis/stalker-to-m3u/tools/generator-config.json
{
  "geminiAiKey": ["INSERT_YOUR_OPENAPI_KEY"],
  "geminiAiModel": "gemini-2.5-flash-preview-09-2025",
  "languages": [
    "French",
    "English"
  ],
  "iptv": {
    "countries": [
      "France",
      "Switzerland",
      "French Canada"
    ],
    "excludedGroups": [
      "Adults",
      "SD channels",
      "Sports",
      "Music"
    ]
  },
  "vod": {
    "includedCategories": [
      "All groups of supported languages I requested",
      "Multi sub"
    ],
    "excludedCategories": [
      "Anime",
      "Adults",
      "Rated R",
      "Romance",
      "Drama",
      "Christmas",
      "Western",
      "Foreign movies",
      "Apple"
    ]
  },
  "series": {
    "includedSeries": [
      "Black Mirror",
      "Hellbound"
    ]
  },
  "streamTester": "ffmpeg"
}
